# Generated by Django 4.2.3 on 2023-07-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignalApp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnployeeDetails',
            new_name='EmployeeDetails',
        ),
    ]
